name: First Worklow
on: workflow_dispatch
jobs:
  first-job:
    runs-on: ubuntu-latest
    steps:
      - name: Print Greeting in Multiline
        run: |
          echo "Hello World from Bhawesh"
          echo "this is a multiline print"
          echo "multi line ends"
      - name: Print GoodBye
        run: echo "Done -Bye!"
      - name: Bhawesh Acknowledgement
        run: echo "Acknowledgement from Bhawesh"

