name: Learning Configuration Variables
on:
  workflow_dispatch
env:
  # Setting an environment variable with the value of a configuration variable
  env_var: ${{ vars.ENV_CONTEXT_VAR }}
jobs:
  greeting_job:
    runs-on: ubuntu-latest
    steps:
      - name: "Displaying Hobby"
        run: |
         echo "My hobby is ${{vars.MY_HOBBY}}"
         echo "git hub ref ${{ github.ref }}"
         echo "repo name ${{ github.repository }}"
         echo "event name ${{ github.event }}"
